---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-hdd
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  type: ceph-hdd
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: ceph-ssd
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
